console.log('script.js loaded')

// Clear form button functionality
const refreshButton = document.getElementById('refreshButton');

refreshButton.addEventListener('click', () => {
  location.reload();
});

//Auto-fill website and NAIC
document.addEventListener("DOMContentLoaded", function () {
  const insurerWebsites = {
   "21St Century Insurance Company": "https://www.21st.com/",
"Accredited Surety and Casualty Company, Inc.": "https://www.accreditedinsurance.com/",
"Aegis Security Insurance Company": "https://www.aegisinsco.com/",
"AIG Property Casualty Company": "https://www.aig.com/",
"Allianz Underwriters Insurance Company": "https://commercial.allianz.com/",
"Allstate Insurance Company": "https://www.allstate.com",
"Allstate Property and Casualty Insurance Company": "https://www.allstate.com",
"American Modern Home Insurance Company": "https://amig.com",
"American Modern Property & Casualty Insurance Company": "https://amig.com/",
"American National Property and Casualty Company": "https://www.americannational.com/",
"Amguard Insurance Company": "https://www.guard.com/",
"Anchor General Insurance Company": "https://www.anchorgeneral.com/",
"Berkley Insurance Company": "https://www.berkley.com/",
"Berkshire Hathaway Direct Insurance Company": "https://www.nationalindemnity.com/",
"California Automobile Insurance Company": "https://www.mercuryinsurance.com/",
"Chubb Indemnity Insurance Company": "https://www.chubb.com",
"Chubb National Insurance Company": "https://www.chubb.com",
"Cincinnati Insurance Company (The)": "https://www.cinfin.com/",
"DB Insurance Co. Ltd. (US BRANCH)": "http://www.dbinsus.com/",
"Encompass Insurance Company": "https://www.allstate.com",
"Farmers Insurance Company, Inc.": "https://www.farmers.com",
"Farmers Insurance Exchange": "https://www.farmers.com",
"Federal Insurance Company": "https://www.chubb.com",
"Fire Insurance Exchange": "https://www.farmers.com",
"Foremost Insurance Company Grand Rapids, MI": "https://www.foremost.com",
"Foremost Property and Casualty Insurance Company": "https://www.foremost.com",
"Foremost Signature Insurance Company": "https://www.foremost.com",
"General Insurance Company Of America": "https://www.safeco.com/",
"Great American Insurance Company": "https://www.greatamericaninsurancegroup.com/",
"Hartford Casualty Insurance Company": "https://www.thehartford.com",
"Hartford Fire Insurance Company": "https://www.thehartford.com",
"Hiscox Insurance Company Inc.": "https://www.hiscox.com/",
"Homesite Insurance Company Of California": "https://go.homesite.com/",
"Liberty Insurance Corporation": "https://www.libertymutualgroup.com/",
"Markel Insurance Company": "https://www.markel.com/",
"Mercury Casualty Company": "https://www.mercuryinsurance.com/",
"Mid-Century Insurance Company": "https://www.farmers.com",
"Midvale Indemnity Company": "https://www.amfam.com/",
"National General Insurance Company": "https://nationalgeneral.com/",
"Nationwide General Insurance Company": "https://www.nationwide.com",
"Nationwide Insurance Company Of America": "https://www.nationwide.com",
"Nationwide Mutual Insurance Company": "https://www.nationwide.com",
"Navigators Insurance Company": "https://www.thehartford.com/",
"NEXT INSURANCE US COMPANY": "https://www.nextinsurance.com/",
"Northland Insurance Company": "https://www.northlandins.com/",
"Pacific Specialty Insurance Company": "https://www.pacificspecialty.com/",
"Philadelphia Indemnity Insurance Company": "https://www.phly.com/",
"Privilege Underwriters Reciprocal Exchange": "https://www.pureinsurance.com/",
"Progressive Casualty Insurance Company": "https://www.progressive.com/",
"Safeco Insurance Company Of America": "https://www.safeco.com/",
"Safeco Insurance Company Of Illinois": "https://www.safeco.com/",
"Seaview Insurance Company": "https://www.svinsco.com/",
"Sentinel Insurance Company, Ltd.": "https://www.thehartford.com",
"Spinnaker Insurance Company": "https://spinnakerins.com/",
"Standard Fire Insurance Company (The)": "https://www.travelers.com",
"State Farm Fire and Casualty Company": "https://www.statefarm.com/",
"State Farm General Insurance Company": "https://www.statefarm.com/",
"State Farm Mutual Automobile Insurance Company": "https://www.statefarm.com/",
"Stillwater Insurance Company": "https://stillwaterinsurance.com/",
"Sutton National Insurance Company": "https://suttonnational.com/",
"Tokio Marine America Insurance Company": "https://www.tmamerica.com/",
"Travelers Casualty and Surety Company": "https://www.travelers.com",
"Travelers Casualty and Surety Company Of America": "https://www.travelers.com",
"Travelers Casualty Insurance Company Of America": "https://www.travelers.com",
"Travelers Commercial Casualty Company": "https://www.travelers.com",
"Travelers Indemnity Company (The)": "https://www.travelers.com",
"Travelers Indemnity Company of America (The)": "https://www.travelers.com",
"Travelers Property Casualty Insurance Company": "https://www.travelers.com",
"Truck Insurance Exchange": "https://www.farmers.com",
"Underwriters at Lloyds, London": "https://www.lloyds.com/",
"United Services Automobile Association": "https://www.usaa.com/",
"United States Liability Insurance Company": "https://www.usli.com/",
"USAA Casualty Insurance Company": "https://www.usaa.com/",
"Westchester Fire Insurance Company": "https://www.chubb.com/us-en/",
"Liberty Mutual Insurance Company": "https://www.libertymutual.com"
  };

  const insurerNaic = {
"21St Century Insurance Company": "12963",
"Accredited Surety and Casualty Company, Inc.": "26379",
"Aegis Security Insurance Company": "33898",
"AIG Property Casualty Company": "19402",
"Allianz Underwriters Insurance Company": "36420",
"Allstate Insurance Company": "19232",
"Allstate Property and Casualty Insurance Company": "17230",
"American Modern Home Insurance Company": "23469",
"American Modern Property & Casualty Insurance Company": "42722",
"American National Property and Casualty Company": "28401",
"Amguard Insurance Company": "42390",
"Anchor General Insurance Company": "40010",
"Berkley Insurance Company": "32603",
"Berkshire Hathaway Direct Insurance Company": "10391",
"California Automobile Insurance Company": "38342",
"Chubb Indemnity Insurance Company": "12777",
"Chubb National Insurance Company": "10052",
"Cincinnati Insurance Company (The)": "10677",
"DB Insurance Co. Ltd. (US BRANCH)": "12502",
"Encompass Insurance Company": "10358",
"Farmers Insurance Company, Inc.": "21628",
"Farmers Insurance Exchange": "21652",
"Federal Insurance Company": "20281",
"Fire Insurance Exchange": "21660",
"Foremost Insurance Company Grand Rapids, MI": "11185",
"Foremost Property and Casualty Insurance Company": "11800",
"Foremost Signature Insurance Company": "41513",
"General Insurance Company Of America": "24732",
"Great American Insurance Company": "16691",
"Hartford Casualty Insurance Company": "29424",
"Hartford Fire Insurance Company": "19682",
"Hiscox Insurance Company Inc.": "10200",
"Homesite Insurance Company Of California": "11005",
"Liberty Insurance Corporation": "42404",
"Markel Insurance Company": "38970",
"Mercury Casualty Company": "11908",
"Mid-Century Insurance Company": "21687",
"Mid-Century Insurance Company": "21687",
"Midvale Indemnity Company": "27138",
"National General Insurance Company": "23728",
"Nationwide General Insurance Company": "23760",
"Nationwide Insurance Company Of America": "25453",
"Nationwide Mutual Insurance Company": "23787",
"Navigators Insurance Company": "42307",
"NEXT INSURANCE US COMPANY": "16285",
"Northland Insurance Company": "24015",
"Pacific Specialty Insurance Company": "37850",
"Philadelphia Indemnity Insurance Company": "18058",
"Privilege Underwriters Reciprocal Exchange": "12873",
"Progressive Casualty Insurance Company": "24260",
"Safeco Insurance Company Of America": "24740",
"Safeco Insurance Company Of Illinois": "39012",
"Seaview Insurance Company": "10004",
"Sentinel Insurance Company, Ltd.": "11000",
"Spinnaker Insurance Company": "24376",
"Standard Fire Insurance Company (The)": "19070",
"State Farm Fire and Casualty Company": "25143",
"State Farm General Insurance Company": "25151",
"State Farm Mutual Automobile Insurance Company": "25178",
"Stillwater Insurance Company": "25180",
"Sutton National Insurance Company": "25798",
"Tokio Marine America Insurance Company": "10945",
"Travelers Casualty and Surety Company": "19038",
"Travelers Casualty and Surety Company Of America": "31194",
"Travelers Casualty Insurance Company Of America": "19046",
"Travelers Commercial Casualty Company": "40282",
"Travelers Indemnity Company (The)": "25658",
"Travelers Indemnity Company of America (The)": "25666",
"Travelers Property Casualty Insurance Company": "36161",
"Truck Insurance Exchange": "21709",
"Underwriters at Lloyds, London": "32727",
"United Services Automobile Association": "25941",
"United States Liability Insurance Company": "25895",
"USAA Casualty Insurance Company": "25968",
"Westchester Fire Insurance Company": "10030",
"21St Century Casualty Company": "36404",
"5 Star Life Insurance Company": "77879",
"Aaa Life Insurance Company": "71854",
"Aca Financial Guaranty Corporation": "22896",
"Aca Insurance Company": "10921",
"Acacia Life Insurance Company": "60038",
"Accendo Insurance Company": "63444",
"Acceptance Indemnity Insurance Company": "20010",
"Access Insurance Company": "11711",
"Accident Fund Insurance Company Of America": "10166",
"Ace American Insurance Company": "22667",
"Ace Capital Title Reinsurance Company": "50028",
"Ace Fire Underwriters Insurance Company": "20702",
"Ace Life Insurance Company": "60348",
"Ace Property and Casualty Insurance Company": "20699",
"Acig Insurance Company": "19984",
"Acstar Insurance Company": "22950",
"Admiral Life Insurance Company Of America": "71390",
"Advantage Workers Compensation Insurance Company": "40517",
"Aetna Health and Life Insurance Company": "78700",
"Aetna Insurance Company Of Connecticut": "36153",
"Aetna Life Insurance Company": "60054",
"Affiliated Fm Insurance Company": "10014",
"Affirmative Insurance Company": "42609",
"Agcs Marine Insurance Company": "22837",
"Agl Life Assurance Company": "60232",
"Agri General Insurance Company": "42757",
"Aig Centennial Insurance Company": "34789",
"Aig Indemnity Insurance Company": "43974",
"Aig Life Insurance Company": "66842",
"Aig Preferred Insurance Company": "22225",
"Aig Premier Insurance Company": "20796",
"Aioi Insurance Company Of America": "34886",
"Aiu Insurance Company": "19399",
"Alaska National Insurance Company": "38733",
"Alea North America Insurance Company": "24899",
"All America Insurance Company": "20222",
"All Savers Life Insurance Company Of California": "73130",
"Allegheny Casualty Company": "13285",
"Alliance Assurance Company Of America": "20273",
"Alliance United Insurance Company": "10920",
"Allianz Global Risks Us Insurance Company": "35300",
"Allianz Life and Annuity Company": "69604",
"Allianz Life Insurance Company Of North America": "90611",
"Allied Property and Casualty Insurance Company": "42579",
"Allied World Assurance Company (U.S.) Inc.": "19489",
"Allied World Reinsurance Company": "22730",
"Allmerica Financial Benefit Insurance Company": "41840",
"Allstate Assurance Company": "70866",
"Allstate Indemnity Company": "19240",
"Allstate Life Insurance Company": "60186",
"Allstate Life Insurance Company Of New York": "70874",
"Alta Health & Life Insurance Company": "67369",
"Amalgamated Life and Health Insurance Company": "60208",
"Amalgamated Life Insurance Company": "60216",
"Ambac Assurance Corporation": "18708",
"Amco Insurance Company": "19100",
"American Alternative Insurance Corporation": "19720",
"American Automobile Insurance Company": "21849",
"American Bankers Insurance Company Of Florida": "10111",
"American Bankers Life Assurance Company Of Florida": "60275",
"American Capitol Insurance Company": "60291",
"American Casualty Company Of Reading, Pennsylvania": "20427",
"American Commerce Insurance Company": "19941",
"American Contractors Indemnity Company": "10216",
"American Economy Insurance Company": "19690",
"American Empire Insurance Company": "37990",
"American Equity Investment Life Insurance Company": "92738",
"American Equity Specialty Insurance Company": "10819",
"American Family Home Insurance Company": "23450",
"American Family Life Assurance Company Of Columbus": "60380",
"American Family Life Insurance Company": "60399",
"American Farmers & Ranchers Insurance Company": "37931",
"American Federation Insurance Company": "43699",
"American Fidelity Assurance Company": "60410",
"American Fidelity Life Insurance Company": "60429",
"American Fire and Casualty Company": "24066",
"American Fraternal Union": "56200",
"American Fuji Fire and Marine Insurance Company": "40398",
"American General Assurance Company": "68373",
"American General Life and Accident Insurance Company": "66672",
"American General Life Insurance Company": "60488",
"American General Property Insurance Company": "31208",
"American Guarantee and Liability Insurance Company": "26247",
"American Guaranty Title Insurance Company": "51411",
"American Hardware Mutual Insurance Company": "13331",
"American Health and Life Insurance Company": "60518",
"American Healthcare Indemnity Company": "39152",
"American Heritage Life Insurance Company": "60534",
"American Home Assurance Company": "19380",
"American Income Life Insurance Company": "60577",
"American Insurance Company (The)": "21857",
"American International Insurance Company Of California, Inc.": "43761",
"American International Life Assurance Company Of New York": "60607",
"American Interstate Insurance Company": "31895",
"American Life and Health Insurance Company": "60674",
"American Manufacturers Mutual Insurance Company": "30562",
"American Maturity Life Insurance Company": "81213",
"American Medical Security Life Insurance Company": "97179",
"American Memorial Life Insurance Company": "67989",
"American Merchants Casualty Company": "43630",
"American Mercury Insurance Company": "16810",
"American Modern Life Insurance Company": "65811",
"American Motorists Insurance Company": "22918",
"American National General Insurance Company": "39942",
"American National Insurance Company": "60739",
"American National Life Insurance Company Of Texas": "71773",
"American Network Insurance Company": "81078",
"American Pet Insurance Company": "12190",
"American Phoenix Life and Reassurance Company": "91785",
"American Professionals Insurance Company": "12084",
"American Public Life Insurance Company": "60801",
"American Reliable Insurance Company": "19615",
"American Republic Insurance Company": "60836",
"American Road Insurance Company (The)": "19631",
"American Safety Casualty Insurance Company": "39969",
"American Security Insurance Company": "42978",
"American Specialty Health Insurance Company": "84697",
"American States Insurance Company": "19704",
"American States Insurance Company Of Texas": "19712",
"American States Preferred Insurance Company": "37214",
"American Sterling Insurance Company": "40800",
"American Surety Company": "31380",
"American United Life Insurance Company": "60895",
"American Zurich Insurance Company": "40142",
"American-Amicable Life Insurance Company Of Texas": "68594",
"Americas Insurance Company": "27898",
"Americo Financial Life and Annuity Insurance Company": "61999",
"Amerin Guaranty Corporation": "30872",
"Amerisure Mutual Insurance Company": "23396",
"Ameritas Life Insurance Corp.": "61301",
"Amex Assurance Company": "27928",
"Amica Life Insurance Company": "72222",
"Amica Mutual Insurance Company": "19976",
"Annuity Investors Life Insurance Company": "93661",
"Anthem Alliance Health Insurance Company": "85286",
"Anthem Blue Cross Life and Health Insurance Company": "62825",
"Anthem Life Insurance Company": "61069",
"Arag Insurance Company": "34738",
"Arch Indemnity Insurance Company": "30830",
"Arch Insurance Company": "11150",
"Arch Reinsurance Company": "10348",
"Argonaut Great Central Insurance Company": "19860",
"Argonaut Insurance Company": "19801",
"Argonaut-Midwest Insurance Company": "19828",
"Argonaut-Southwest Insurance Company": "19844",
"Armed Forces Insurance Exchange": "41459",
"Armor Assurance Company": "10632",
"Arrowood Indemnity Company": "24678",
"Associated Indemnity Corporation": "21865",
"Associated International Insurance Company": "27189",
"Assurance Company Of America": "19305",
"Assured Guaranty Corp.": "30180",
"Assurity Life Insurance Company": "71439",
"Athena Assurance Company": "41769",
"Atlanta International Insurance Company": "20931",
"Atlantic Insurance Company": "22209",
"Atlantic Mutual Insurance Company": "19895",
"Atlantic Specialty Insurance Company": "27154",
"Atradius Trade Credit Insurance, Inc.": "25422",
"Aurora National Life Assurance Company": "61182",
"Auto Club Life Insurance Company": "84522",
"Automobile Club Of Southern California Life Insurance Company": "60256",
"Autoone Insurance Company": "34460",
"Avemco Insurance Company": "10367",
"Aviva Life and Annuity Company": "61689",
"Axa Art Insurance Corporation": "29530",
"Axa Corporate Solutions Life Reinsurance Company": "68365",
"Axa Equitable Life and Annuity Company": "62880",
"Axa Equitable Life Insurance Company": "62944",
"Axa Insurance Company": "33022",
"Axa Re Property and Casualty Insurance Company": "16187",
"Axis Insurance Company": "37273",
"Axis Reinsurance Company": "20370",
"Balboa Insurance Company": "24813",
"Balboa Life Insurance Company": "68160",
"Baltimore Life Insurance Company (The)": "61212",
"Bancinsure, Inc.": "18538",
"Bankers Insurance Company": "33162",
"Bankers Life and Casualty Company": "61263",
"Bankers Standard Insurance Company": "18279",
"Banner Life Insurance Company": "94250",
"Baptist Life Association": "57223",
"Bar Plan Mutual Insurance Company (The)": "29513",
"Bcs Insurance Company": "38245",
"Bcs Life Insurance Company": "80985",
"Beazley Insurance Company, Inc.": "37540",
"Benchmark Insurance Company": "41394",
"Beneficial Life Insurance Company": "61395",
"Berkley Life and Health Insurance Company": "64890",
"Berkley Regional Insurance Company": "29580",
"Berkshire Hathaway Assurance Corporation": "13070",
"Berkshire Hathaway Life Insurance Company Of Nebraska": "62345",
"Berkshire Life Insurance Company Of America": "71714",
"Best Life and Health Insurance Company": "90638",
"Bituminous Casualty Corporation": "20095",
"Bituminous Fire and Marine Insurance Company": "20109",
"Blue Ridge Insurance Company": "24503",
"Blue Shield Of California Life & Health Insurance Company": "61557",
"Bond Safeguard Insurance Company": "27081",
"Boston Mutual Life Insurance Company": "61476",
"Brokers National Life Assurance Company": "74900",
"Brotherhood Mutual Insurance Company": "13528",
"Business Alliance Insurance Company": "10830",
"C.M. Life Insurance Company": "93432",
"C.P.A. Insurance Company": "30082",
"California Capital Insurance Company": "13544",
"California Casualty & Fire Insurance Company": "27464",
"California Casualty Compensation Insurance Company": "10063",
"California Casualty General Insurance Company Of Oregon": "35955",
"California Casualty Indemnity Exchange (The)": "20117",
"California Casualty Insurance Company": "20125",
"California General Underwriters Insurance Company, Inc.": "31046",
"California Insurance Company": "38865",
"California Mutual Insurance Company": "27480",
"California State Automobile Association Inter-Insurance Bureau": "15539",
"Camden Fire Insurance Association (The)": "21946",
"Camico Mutual Insurance Company": "36340",
"Canada Life Assurance Company (The)": "80659",
"Canada Life Insurance Company Of America": "81060",
"Canal Insurance Company": "10464",
"Capital Markets Assurance Corporation": "20877",
"Capitol Indemnity Corporation": "10472",
"Capitol Life Insurance Company (The)": "61581",
"Cardif Life Insurance Company": "71455",
"Cardif Property and Casualty Insurance Company": "21075",
"Care West Insurance Company": "10520",
"Careamerica Life Insurance Company": "71331",
"Carolina Casualty Insurance Company": "10510",
"Caterpillar Insurance Company": "11255",
"Caterpillar Life Insurance Company": "11997",
"Catholic Family Life Insurance": "56022",
"Catholic Knights": "56030",
"Catholic Order Of Foresters": "57487",
"Catholic Relief Insurance Company Of America (The)": "10561",
"Catlin Insurance Company, Inc.": "19518",
"Celtic Insurance Company": "80799",
"Censtat Casualty Company": "11499",
"Centennial Insurance Company": "19909",
"Central Benefits National Life Insurance Company": "63541",
"Central Mutual Insurance Company": "20230",
"Central States Health & Life Co. Of Omaha": "61751",
"Central States Indemnity Co. Of Omaha": "34274",
"Central United Life Insurance Company": "61883",
"Centre Insurance Company": "34649",
"Centurion Casualty Company": "42765",
"Centurion Life Insurance Company": "62383",
"Century Indemnity Company": "20710",
"Century Reinsurance Company": "35130",
"Century-National Insurance Company": "26905",
"Charter National Life Insurance Company": "61808",
"Cherokee Insurance Company": "10642",
"Chesapeake Life Insurance Company (The)": "61832",
"Chicago Insurance Company": "22810",
"Chicago Title Insurance Company": "50229",
"Chrysler Insurance Company": "10499",
"Church Insurance Company (The)": "10669",
"Church Life Insurance Corporation": "61875",
"Church Mutual Insurance Company": "18767",
"Cifg Assurance North America, Inc.": "25771",
"Cim Insurance Corporation": "22004",
"Cincinnati Life Insurance Company (The)": "76236",
"Citation Insurance Company": "42242",
"Civic Property and Casualty Company": "10315",
"Civil Service Employees Insurance Company": "10693",
"Claremont Liability Insurance Company": "36412",
"Clarendon National Insurance Company": "20532",
"Clearwater Insurance Company": "25070",
"Cmg Mortgage Assurance Company": "29114",
"Cmg Mortgage Insurance Company": "40266",
"Coast National Insurance Company": "25089",
"Coface North America Insurance Company": "31887",
"Coliseum Reinsurance Company": "36552",
"Cologne Reinsurance Company Of America": "33197",
"Colonial American Casualty and Surety Company": "34347",
"Colonial Life & Accident Insurance Company": "62049",
"Colonial Penn Life Insurance Company": "62065",
"Colonial Surety Company": "10758",
"Colorado Bankers Life Insurance Company": "84786",
"Columbia Insurance Company": "27812",
"Columbian Life Insurance Company": "76023",
"Columbian Mutual Life Insurance Company": "62103",
"Columbus Life Insurance Company": "99937",
"Combined Insurance Company Of America": "62146",
"Commerce and Industry Insurance Company": "19410",
"Commerce Title Insurance Company": "50026",
"Commerce West Insurance Company": "13161",
"Commercial Casualty Insurance Company": "32280",
"Commercial Guaranty Insurance Company": "38385",
"Commercial Loan Insurance Corporation": "18732",
"Commercial Travelers Mutual Insurance Company": "81426",
"Commonwealth Annuity and Life Insurance Company": "84824",
"Commonwealth Insurance Company Of America": "10220",
"Commonwealth Land Title Insurance Company": "50083",
"Companion Property and Casualty Insurance Company": "12157",
"Compass Insurance Company": "21989",
"Computer Insurance Company": "34711",
"Compwest Insurance Company": "12177",
"Congress Life Insurance Company": "73504",
"Connecticut General Life Insurance Company": "62308",
"Conseco Health Insurance Company": "78174",
"Conseco Insurance Company": "60682",
"Conseco Life Insurance Company": "65900",
"Conselho Supremo Da Uniao Portugueza Do Estado Da California (U.P.E.C.)": "57940",
"Constitution Insurance Company": "32190",
"Constitution Life Insurance Company": "62359",
"Continental American Insurance Company": "71730",
"Continental Assurance Company": "62413",
"Continental Casualty Company": "20443",
"Continental General Insurance Company": "71404",
"Continental Heritage Insurance Company": "39551",
"Continental Insurance Company (The)": "35289",
"Contractors Bonding and Insurance Company": "37206",
"Cornerstone National Insurance Company": "10783",
"Cornhusker Casualty Company": "20044",
"Courtesy Insurance Company": "26492",
"Cranbrook Insurance Company": "29033",
"Crestbrook Insurance Company": "18961",
"Croatian Fraternal Union Of America": "56634",
"Crown Life Insurance Company": "80675",
"Crusader Insurance Company": "14010",
"Csa Fraternal Life": "56138",
"Cse Safeguard Insurance Company": "18953",
"Csi Life Insurance Company": "82880",
"Cumis Insurance Society, Inc.": "10847",
"Cuna Mutual Insurance Society": "62626",
"Cypress Insurance Company": "10855",
"Dallas National Insurance Company, A Texas Stock Insurance Company": "32271",
"Danielson National Insurance Company": "19269",
"Darwin National Assurance Company": "16624",
"Dealers Assurance Company": "16705",
"Deerbrook Insurance Company": "37907",
"Degree Of Honor Protective Association": "57088",
"Delaware American Life Insurance Company": "62634",
"Delos Insurance Company": "35408",
"Delta Dental Insurance Company": "81396",
"Dentegra Insurance Company": "73474",
"Dentists Insurance Company (The)": "40975",
"Depositors Insurance Company": "42587",
"Developers Surety and Indemnity Company": "12718",
"Diamond State Insurance Company": "42048",
"Discover Property & Casualty Insurance Company": "36463",
"Doctors' Company, An Interinsurance Exchange (The)": "34495",
"Doctors' Life Insurance Company (The)": "92444",
"Dorinco Reinsurance Company": "33499",
"Eagle Life Insurance Company": "13183",
"Eagle West Insurance Company": "12890",
"Eastguard Insurance Company": "14702",
"Economy Fire & Casualty Company": "22926",
"Electric Insurance Company": "21261",
"Emc National Life Company": "62928",
"Emcasco Insurance Company": "21407",
"Empire Fire and Marine Insurance Company": "21326",
"Employees Life Company (Mutual)": "84174",
"Employers Compensation Insurance Company": "11512",
"Employers Direct Insurance Company": "11555",
"Employers' Fire Insurance Company (The)": "20648",
"Employers Insurance Company Of Wausau": "21458",
"Employers Mutual Casualty Company": "21415",
"Employers Reassurance Corporation": "68276",
"Endurance Reinsurance Corporation Of America": "11551",
"Entitle Insurance Company": "51632",
"Equitrust Life Insurance Company": "62510",
"Equity Insurance Company": "28746",
"Essentia Insurance Company": "37915",
"Esurance Insurance Company": "25712",
"Esurance Property and Casualty Insurance Company": "30210",
"Euler Hermes American Credit Indemnity Company": "20516",
"Everest National Insurance Company": "10120",
"Everest Reinsurance Company": "26921",
"Evergreen National Indemnity Company": "12750",
"Everspan Financial Guarantee Corp.": "24961",
"Exact Property and Casualty Company": "10318",
"Executive Risk Indemnity Inc.": "35181",
"Explorer Insurance Company": "40029",
"Factory Mutual Insurance Company": "21482",
"Fairfield Insurance Company": "44784",
"Fairmont Insurance Company": "18864",
"Fairmont Premier Insurance Company": "25518",
"Fairmont Specialty Insurance Company": "24384",
"Family Heritage Life Insurance Company Of America": "77968",
"Family Life Insurance Company": "63053",
"Family Service Life Insurance Company": "74004",
"Farmers Insurance Company Of Oregon": "21636",
"Farmers Insurance Exchange": "21652",
"Farmers Mutual Hail Insurance Company Of Iowa": "13897",
"Farmers New World Life Insurance Company": "63177",
"Farmers Reinsurance Company": "10873",
"Farmington Casualty Company": "41483",
"Farmland Mutual Insurance Company": "13838",
"Federal Life Insurance Company (Mutual)": "63223",
"Federated Life Insurance Company": "63258",
"Federated Mutual Insurance Company": "13935",
"Federated Rural Electric Insurance Exchange": "11118",
"Federated Service Insurance Company": "28304",
"Ffg Insurance Company": "43460",
"Fidelity and Deposit Company Of Maryland": "39306",
"Fidelity and Guaranty Insurance Company": "35386",
"Fidelity and Guaranty Insurance Underwriters, Inc.": "25879",
"Fidelity Investments Life Insurance Company": "93696",
"Fidelity Life Association, A Legal Reserve Life Insurance Company": "63290",
"Fidelity National Property and Casualty Insurance Company": "16578",
"Fidelity National Title Insurance Company": "51586",
"Fidelity Security Life Insurance Company": "71870",
"Financial Casualty & Surety,  Inc.": "35009",
"Financial Guaranty Insurance Company": "12815",
"Financial Indemnity Company": "19852",
"Financial Pacific Insurance Company": "31453",
"Financial Security Assurance Inc.": "18287",
"Finial Reinsurance Company": "39136",
"Fireman'S Fund Insurance Company": "21873",
"First Allmerica Financial Life Insurance Company": "69140",
"First American Property & Casualty Insurance Company": "37710",
"First American Specialty Insurance Company": "34525",
"First American Title Insurance Company": "50814",
"First Continental Life & Accident Insurance Co.": "64696",
"First Financial Insurance Company": "11177",
"First Health Life & Health Insurance Company": "90328",
"First Investors Life Insurance Company": "63495",
"First Liberty Insurance Corporation (The)": "33588",
"First National Insurance Company Of America": "24724",
"First Penn-Pacific Life Insurance Company": "67652",
"First Pyramid Life Insurance Company Of America (The)": "63533",
"First Sealord Surety, Inc.": "28519",
"First State Insurance Company": "21822",
"Florists' Mutual Insurance Company": "13978",
"Foremost Insurance Company Grand Rapids, Michigan": "11185",
"Forestview Mortgage Insurance Co.": "29688",
"Forethought Life Insurance Company": "91642",
"Fort Dearborn Life Insurance Company": "71129",
"Frontier Insurance Company": "34266",
"Funeral Directors Life Insurance Company": "99775",
"Garden State Life Insurance Company": "63657",
"Garrison Property and Casualty Insurance Company": "21253",
"Gateway Insurance Company": "28339",
"Geico Casualty Company": "41491",
"Geico General Insurance Company": "35882",
"Geico Indemnity Company": "22055",
"General American Life Insurance Company": "63665",
"General Casualty Company Of Wisconsin": "24414",
"General Fidelity Insurance Company": "30007",
"General Fidelity Life Insurance Company": "93521",
"General Re Life Corporation": "86258",
"General Reinsurance Corporation": "22039",
"General Security National Insurance Company": "39322",
"General Star National Insurance Company": "11967",
"Generali Assicurazioni Generali S.P.A. (U.S. Branch)": "11231",
"Generali Usa Life Reassurance Company": "97071",
"Genesis Insurance Company": "38962",
"Genworth Home Equity Insurance Corporation": "41432",
"Genworth Life and Annuity Insurance Company": "65536",
"Genworth Life Insurance Company": "70025",
"Genworth Mortgage Insurance Corporation": "38458",
"Genworth Mortgage Insurance Corporation Of North Carolina": "16675",
"Genworth Residential Mortgage Assurance Corporation": "18759",
"Genworth Residential Mortgage Insurance Corporation Of North Carolina": "29823",
"Geovera Insurance Company": "10799",
"Geovera Specialty Insurance Company": "10182",
"Gerber Life Insurance Company": "70939",
"Germantown Insurance Company": "11282",
"Global Reinsurance Corporation": "11266",
"Global Reinsurance Corporation Of America": "21032",
"Global Surety & Insurance Co.": "11304",
"Globe Life and Accident Insurance Company": "91472",
"Gmac Insurance Company Online, Inc.": "11044",
"Golden Bear Insurance Company": "39861",
"Golden Eagle Insurance Corporation": "10836",
"Golden Rule Insurance Company": "62286",
"Government Employees Insurance Company": "22063",
"Government Personnel Mutual Life Insurance Company": "63967",
"Grain Dealers Mutual Insurance Company": "22098",
"Grange Insurance Association": "22101",
"Granite State Insurance Company": "23809",
"Graphic Arts Mutual Insurance Company": "25984",
"Gray Insurance Company (The)": "36307",
"Great American Alliance Insurance Company": "26832",
"Great American Assurance Company": "26344",
"Great American Contemporary Insurance Company": "10646",
"Great American Insurance Company Of New York": "22136",
"Great American Life Assurance Company": "62200",
"Great American Life Insurance Company": "63312",
"Great American Protection Insurance Company": "38580",
"Great American Security Insurance Company": "31135",
"Great American Spirit Insurance Company": "33723",
"Great Divide Insurance Company": "25224",
"Great Northern Insurance Company": "20303",
"Great Southern Life Insurance Company": "90212",
"Great West Casualty Company": "11371",
"Great Western Insurance Company": "71480",
"Greater Beneficial Union Of Pittsburgh": "56685",
"Great-West Life & Annuity Insurance Company": "68322",
"Great-West Life Assurance Company (The)": "80705",
"Greek Catholic Union Of The U.S.A.": "56693",
"Greenwich Insurance Company": "22322",
"Guarantee Company Of North America Usa (The)": "36650",
"Guarantee Insurance Company": "11398",
"Guarantee Trust Life Insurance Company": "64211",
"Guaranty Income Life Insurance Company": "64238",
"Guardian Insurance & Annuity Company, Inc. (The)": "78778",
"Guardian Life Insurance Company Of America (The)": "64246",
"Guideone Mutual Insurance Company": "15032",
"Guideone Specialty Mutual Insurance Company": "14559",
"Hallmark Insurance Company": "34037",
"Hannover Life Reassurance Company Of America": "88340",
"Hanover Insurance Company (The)": "22292",
"Harbor Point Reinsurance U.S., Inc.": "10829",
"Harbor Specialty Insurance Company": "21806",
"Harco National Insurance Company": "26433",
"Harleysville Insurance Company": "23582",
"Harleysville Mutual Insurance Company": "14168",
"Hartford Accident and Indemnity Company": "22357",
"Hartford Insurance Company Of The Midwest": "37478",
"Hartford International Life Reassurance Corporation": "93505",
"Hartford Life and Accident Insurance Company": "70815",
"Hartford Life and Annuity Insurance Company": "71153",
"Hartford Life Insurance Company": "88072",
"Hartford Steam Boiler Inspection and Insurance Company (The)": "11452",
"Hartford Underwriters Insurance Company": "30104",
"Hcc Life Insurance Company": "92711",
"Hcsc Insurance Services Company": "78611",
"Hdi-Gerling America Insurance Company": "41343",
"Health Net Life Insurance Company": "66141",
"Healthmarkets Insurance Company": "92908",
"Healthy Alliance Life Insurance Company": "78972",
"Heritage Casualty Insurance Company": "32077",
"Heritage Indemnity Company": "39527",
"Heritage Life Insurance Company": "64394",
"Heritage Union Life Insurance Company": "62421",
"Highlands Insurance Company": "22489",
"Hillstar Insurance Company": "10068",
"Hm Health Insurance Company": "71768",
"Hm Life Insurance Company": "93440",
"Holy Family Society Of U. S. A. (The)": "57770",
"Homesteaders Life Company": "64505",
"Horace Mann Insurance Company": "22578",
"Horace Mann Life Insurance Company": "64513",
"Horace Mann Property & Casualty Insurance Company": "22756",
"Household Life Insurance Company": "93777",
"Housing Enterprise Insurance Company, Inc.": "11206",
"Houston General Insurance Company": "38849",
"Hsbc Insurance Company Of Delaware": "28657",
"Hudson Insurance Company": "25054",
"Humana Insurance Company": "73288",
"Humanadental Insurance Company": "70580",
"Hungarian Reformed Federation Of America (The)": "56553",
"Hyundai Marine & Fire Insurance Co., Ltd.": "10048",
"Ia American Life Insurance Company": "91693",
"Idealife Insurance Company": "97764",
"Ids Property Casualty Insurance Company": "29068",
"Illinois Mutual Life Insurance Company": "64580",
"Imperial Casualty and Indemnity Company": "11487",
"Indemnity Company Of California": "25550",
"Indemnity Insurance Company Of North America": "43575",
"Independence American Insurance Company": "26581",
"Independence Life and Annuity Company": "64602",
"Independent Order Of Foresters (The)": "58068",
"Indiana Lumbermens Mutual Insurance Company": "14265",
"Individual Assurance Company, Life, Health & Accident": "81779",
"Industrial Alliance Pacific Insurance and Financial Services, Inc.": "84514",
"Infinity Auto Insurance Company": "11738",
"Infinity Insurance Company": "22268",
"Infinity Select Insurance Company": "20260",
"Ing Life Insurance and Annuity Company": "86509",
"Ing Usa Annuity and Life Insurance Company": "80942",
"Insurance Company Of Illinois": "26700",
"Insurance Company Of North America": "22713",
"Insurance Company Of The State Of Pennsylvania (The)": "19429",
"Insurance Company Of The West": "27847",
"Insurance Corporation Of New York (The)": "18341",
"Integon National Insurance Company": "29742",
"Integon Preferred Insurance Company": "31488",
"Integrity Life Insurance Company": "74780",
"Interinsurance Exchange Of The Automobile Club": "15598",
"International Fidelity Insurance Company": "11592",
"Investors Insurance Corporation": "64939",
"Investors Life Insurance Company Of North America": "63487",
"Ironshore Indemnity Inc.": "23647",
"Jackson National Life Insurance Company": "65056",
"Jefferson Insurance Company": "11630",
"Jefferson National Life Insurance Company": "64017",
"Jewelers Mutual Insurance Company": "14354",
"John Alden Life Insurance Company": "65080",
"John Hancock Life & Health Insurance Company": "93610",
"John Hancock Life Insurance Company (U.S.A.)": "65838",
"Kaiser Permanente Insurance Company": "60053",
"Kanawha Insurance Company": "65110",
"Kansas City Life Insurance Company": "65129",
"Kemper Independence Insurance Company": "10914",
"Kemper Investors Life Insurance Company": "90557",
"Knights Of Columbus": "58033",
"Kskj Life, American Slovenian Catholic Union": "56227",
"Lafayette Life Insurance Company (The)": "65242",
"Lancer Insurance Company": "26077",
"Landmark Insurance Company": "35637",
"Laurier Indemnity Company": "35246",
"Lawyers' Mutual Insurance Company": "36706",
"Lawyers Title Insurance Corporation": "50024",
"Leading Insurance Group Insurance Co., Ltd (United States Branch)": "37800",
"Lexington National Insurance Corporation": "37940",
"Lexon Insurance Company": "13307",
"Liberty Bankers Life Insurance Company": "68543",
"Liberty Insurance Underwriters Inc.": "19917",
"Liberty Life Assurance Company Of Boston": "65315",
"Liberty Life Insurance Company": "61492",
"Liberty Mutual Fire Insurance Company": "23035",
"Liberty Mutual Insurance Company": "23043",
"Liberty National Life Insurance Company": "65331",
"Liberty Northwest Insurance Corporation": "41939",
"Life Insurance Company Of North America": "65498",
"Life Insurance Company Of The Southwest": "65528",
"Lifecare Assurance Company": "91898",
"Lifesecure Insurance Company": "77720",
"Lifewise Assurance Company": "94188",
"Lincoln Benefit Life Company": "65595",
"Lincoln General Insurance Company": "33855",
"Lincoln Heritage Life Insurance Company": "65927",
"Lincoln Life & Annuity Company Of New York": "62057",
"Lincoln National Life Insurance Company (The)": "65676",
"Lm General Insurance Company": "36447",
"Lm Insurance Corporation": "33600",
"Lm Personal Insurance Company": "36439",
"Lm Property and Casualty Insurance Company": "32352",
"London Life Reinsurance Company": "76694",
"Longevity Insurance Company": "68446",
"Loya Casualty Insurance Company": "12589",
"Loyal American Life Insurance Company": "65722",
"Loyal Christian Benefit Association": "56758",
"Lumber Mutual Insurance Company": "14435",
"Lumbermens Mutual Casualty Company": "22977",
"Lumbermen'S Underwriting Alliance": "23108",
"Luso-American Life Insurance Society": "57967",
"Lyndon Property Insurance Company": "35769",
"Madison National Life Insurance Company, Inc.": "65781",
"Majestic Insurance Company": "42269",
"Mamsi Life and Health Insurance Company": "60321",
"Manhattan Life Insurance Company (The)": "65870",
"Manhattan National Life Insurance Company": "67083",
"Manufacturers Alliance Insurance Company": "36897",
"Mapfre Insurance Company": "23876",
"Markel American Insurance Company": "28932",
"Marquette National Life Insurance Company": "71072",
"Maryland Casualty Company": "19356",
"Massachusetts Bay Insurance Company": "22306",
"Massachusetts Casualty Insurance Company": "80896",
"Massachusetts Mutual Life Insurance Company": "65935",
"Max America Insurance Company": "21296",
"Mbia Insurance Corporation": "12041",
"Medamerica Insurance Company": "69515",
"Medco Containment Life Insurance Company": "63762",
"Medical Insurance Exchange Of California": "32433",
"Medical Protective Company (The)": "11843",
"Medico Insurance Company": "31119",
"Medico Life Insurance Company": "71471",
"Medmarc Casualty Insurance Company": "22241",
"Medmarc Mutual Insurance Company": "32089",
"Mega Life and Health Insurance Company (The)": "97055",
"Members Life Insurance Company": "86126",
"Memic Indemnity Company": "11030",
"Mendota Insurance Company": "33650",
"Mennonite Mutual Aid Association": "57991",
"Merastar Insurance Company": "31968",
"Merced Mutual Insurance Company": "15768",
"Merchants Bonding Company (Mutual)": "14494",
"Mercury Insurance Company": "27553",
"Merit Life Insurance Company": "65951",
"Meritplan Insurance Company": "24821",
"Merrill Lynch Life Insurance Company": "79022",
"Metlife Insurance Company Of Connecticut": "87726",
"Metlife Investors Insurance Company": "93513",
"Metlife Investors Usa Insurance Company": "61050",
"Metropolitan Direct Property and Casualty Insurance Company": "25321",
"Metropolitan Group Property and Casualty Insurance Company": "34339",
"Metropolitan Life Insurance Company": "65978",
"Metropolitan Tower Life Insurance Company": "97136",
"Mga Insurance Company, Inc.": "40150",
"Mgic Credit Assurance Corporation": "10682",
"Mgic Indemnity Corporation": "18740",
"Mgic Mortgage Reinsurance Corporation": "10666",
"Mgic Reinsurance Corporation": "16470",
"Mgic Residential Reinsurance Corporation": "10252",
"Mic General Insurance Corporation": "38660",
"Mic Property and Casualty Insurance Corporation": "38601",
"Michigan Millers Mutual Insurance Company": "14508",
"Middlesex Insurance Company": "23434",
"Midland National Life Insurance Company": "66044",
"Midstates Reinsurance Corporation": "20451",
"Midwest Employers Casualty Company": "23612",
"Mid-West National Life Insurance Company Of Tennessee": "66087",
"Midwestern United Life Insurance Company": "66109",
"Minnesota Lawyers Mutual Insurance Company": "42234",
"Minnesota Life Insurance Company": "66168",
"Mitsui Sumitomo Insurance Company Of America": "20362",
"Mitsui Sumitomo Insurance Usa Inc.": "22551",
"Mma Insurance Company": "74209",
"Mml Bay State Life Insurance Company": "70416",
"Modern Woodmen Of America": "57541",
"Molina Healthcare Insurance Company": "69647",
"Monarch Life Insurance Company": "66265",
"Monterey Insurance Company": "23540",
"Monumental Life Insurance Company": "66281",
"Mony Life Insurance Company": "66370",
"Mony Life Insurance Company Of America": "78077",
"Mortgage Guaranty Insurance Corporation": "29858",
"Motors Insurance Corporation": "22012",
"Mt. Mckinley Insurance Company": "35947",
"Mtl Insurance Company": "66427",
"Munich American Reassurance Company": "66346",
"Munich Reinsurance America, Inc.": "10227",
"Mutual Of America Life Insurance Company": "88668",
"Mutual Of Omaha Insurance Company": "71412",
"National American Insurance Company": "23663",
"National American Insurance Company Of California": "23671",
"National Benefit Life Insurance Company": "61409",
"National Casualty Company": "11991",
"National Catholic Society Of Foresters": "57568",
"National Continental Insurance Company": "10243",
"National Farmers Union Life Insurance Company": "66540",
"National Farmers Union Property and Casualty Company": "16217",
"National Fire Insurance Company Of Hartford": "20478",
"National Foundation Life Insurance Company": "98205",
"National General Assurance Company": "42447",
"National Guardian Life Insurance Company": "66583",
"National Health Insurance Company": "82538",
"National Indemnity Company": "20087",
"National Interstate Insurance Company": "32620",
"National Liability & Fire Insurance Company": "20052",
"National Life Insurance Company": "66680",
"National Public Finance Guarantee Corporation": "23825",
"National Reinsurance Corporation (The)": "34835",
"National Security Fire and Casualty Company": "12114",
"National Slovak Society Of The United States Of America (The)": "56782",
"National Specialty Insurance Company": "22608",
"National Surety Corporation": "21881",
"National Teachers Associates Life Insurance Company": "87963",
"National Title Insurance Of New York, Inc.": "51020",
"National Union Fire Insurance Company Of Pittsburgh, Pa": "19445",
"National Unity Insurance Company": "19119",
"National Western Life Insurance Company": "66850",
"Nations Insurance Company": "13127",
"Nationwide Affinity Insurance Company Of America": "26093",
"Nationwide Agribusiness Insurance Company": "28223",
"Nationwide Life and Annuity Insurance Company": "92657",
"Nationwide Life Insurance Company": "66869",
"Nationwide Mutual Fire Insurance Company": "23779",
"Nationwide Property and Casualty Company": "37877",
"Nau Country Insurance Company": "25240",
"Ncmic Insurance Company": "15865",
"Neighborhood Spirit Property and Casualty Company": "10317",
"Netherlands Insurance Company (The)": "24171",
"New England Life Insurance Company": "91626",
"New England Reinsurance Corporation": "41629",
"New Era Life Insurance Company": "78743",
"New Era Life Insurance Company Of The Midwest": "69698",
"New Hampshire Insurance Company": "23841",
"New York Life and Health Insurance Company": "97705",
"New York Life Insurance and Annuity Corporation": "91596",
"New York Life Insurance Company": "66915",
"New York Marine and General Insurance Company": "16608",
"Newport Insurance Company": "24848",
"Nippon Life Insurance Company Of America": "81264",
"Nipponkoa Insurance Company, Limited": "27073",
"Norcal Mutual Insurance Company": "33200",
"Norguard Insurance Company": "31470",
"North American Company For Life and Health Insurance": "66974",
"North American Elite Insurance Company": "29700",
"North American Specialty Insurance Company": "29874",
"North American Swiss Alliance": "56375",
"North American Title Insurance Company": "50130",
"North Carolina Mutual Life Insurance Company": "67032",
"North Coast Life Insurance Company": "67059",
"North Pointe Insurance Company": "27740",
"North River Insurance Company (The)": "21105",
"North Star Reinsurance Corporation": "22047",
"Northbrook Indemnity Company": "36455",
"Northern Assurance Company Of America (The)": "38369",
"Northern Insurance Company Of New York": "19372",
"Northland Casualty Company": "24031",
"Northwestern Long Term Care Insurance Company": "69000",
"Northwestern Mutual Life Insurance Company (The)": "67091",
"Northwestern Pacific Indemnity Company": "20338",
"Nova Casualty Company": "42552",
"Nylife Insurance Company Of Arizona": "81353",
"Oak River Insurance Company": "34630",
"Occidental Fire & Casualty Company Of North Carolina": "23248",
"Occidental Life Insurance Company Of North Carolina": "67148",
"Ocean Harbor Casualty Insurance Company": "12360",
"Odyssey America Reinsurance Corporation": "23680",
"Ohio Casualty Insurance Company (The)": "24074",
"Ohio Indemnity Company": "26565",
"Ohio National Life Assurance Corporation": "89206",
"Ohio National Life Insurance Company (The)": "67172",
"Ohio State Life Insurance Company (The)": "67180",
"Old American Insurance Company": "67199",
"Old Republic General Insurance Corporation": "24139",
"Old Republic Insurance Company": "24147",
"Old Republic Life Insurance Company": "67261",
"Old Republic National Title Insurance Company": "50520",
"Old Republic Security Assurance Company": "35424",
"Old Republic Surety Company": "40444",
"Old United Casualty Company": "37060",
"Old United Life Insurance Company": "76007",
"Om Financial Life Insurance Company": "63274",
"Omaha Indemnity Company (The)": "12254",
"Omaha Woodmen Life Insurance Society": "57320",
"Omni Insurance Company": "39098",
"Onebeacon America Insurance Company": "20621",
"Onebeacon Insurance Company": "21970",
"Optimum Re Insurance Company": "88099",
"Order Of United Commercial Travelers Of America (The)": "56383",
"Oregon Mutual Insurance Company": "14907",
"Ormond Reinsurance Company": "33030",
"Oxford Life Insurance Company": "76112",
"Ozark National Life Insurance Company": "67393",
"Pacific Employers Insurance Company": "22748",
"Pacific Guardian Life Insurance Company, Limited": "64343",
"Pacific Indemnity Company": "20346",
"Pacific Life & Annuity Company": "97268",
"Pacific Life Insurance Company": "67466",
"Pacific Pioneer Insurance Company": "40550",
"Pacific Property and Casualty Company": "11048",
"Pacific Select Property Insurance Company": "10887",
"Pacificare Life and Health Insurance Company": "70785",
"Pacificare Life Assurance Company": "84506",
"Paco Assurance Company, Inc.": "10222",
"Pan-American Assurance Company": "93459",
"Pan-American Life Insurance Company": "67539",
"Paris Re America Insurance Company": "11835",
"Park Avenue Life Insurance Company": "60003",
"Parker Centennial Assurance Company": "71099",
"Partner Reinsurance Company Of The U.S.": "38636",
"Partnerre Insurance Company Of New York": "10006",
"Pathfinder Insurance Company": "22250",
"Paul Revere Life Insurance Company (The)": "67598",
"Paul Revere Variable Annuity Insurance Company (The)": "67601",
"Peerless Indemnity Insurance Company": "18333",
"Peerless Insurance Company": "24198",
"Peninsular Life Insurance Company": "67636",
"Penn Diversified Insurance and Annuity Company": "69337",
"Penn Insurance and Annuity Company (The)": "93262",
"Penn Mutual Life Insurance Company (The)": "67644",
"Penn Treaty Network America Insurance Company": "63282",
"Penn-America Insurance Company": "32859",
"Pennsylvania General Insurance Company": "21962",
"Pennsylvania Life Insurance Company": "67660",
"Pennsylvania Lumbermens Mutual Insurance Company": "14974",
"Pennsylvania Manufacturers' Association Insurance Company": "12262",
"Pennsylvania Manufacturers Indemnity Company": "41424",
"Perico Life Insurance Company": "85561",
"Permanent General Assurance Corporation": "37648",
"Personal Express Insurance Company": "12832",
"Petroleum Casualty Company": "12297",
"Pharmacists Life Insurance Company (The)": "90247",
"Pharmacists Mutual Insurance Company": "13714",
"Philadelphia American Life Insurance Company": "67784",
"Philadelphia Reinsurance Corporation": "12319",
"Phl Variable Insurance Company": "93548",
"Phoenix Life Insurance Company": "67814",
"Physicians Life Insurance Company": "72125",
"Physicians Mutual Insurance Company": "80578",
"Pioneer American Insurance Company": "67873",
"Pioneer Mutual Life Insurance Company, A Stock Subsidiary Of American United Mutual Insurance Holding Company": "67911",
"Pioneer Security Life Insurance Company": "67946",
"Platte River Insurance Company": "18619",
"Plaza Insurance Company": "30945",
"Pma Capital Insurance Company": "39675",
"Pmi Insurance Co.": "10287",
"Pmi Mortgage Insurance Co.": "27251",
"Podiatry Insurance Company Of America, A Mutual Company": "14460",
"Police and Firemen'S Insurance Association": "58009",
"Polish National Alliance Of The United States Of North America": "57622",
"Polish Roman Catholic Union Of America": "57630",
"Polish Women'S Alliance Of America": "57649",
"Praetorian Insurance Company": "37257",
"Preferred Employers Insurance Company": "10900",
"Preferred Professional Insurance Company": "36234",
"Premier Access Insurance Company": "60237",
"Preserver Insurance Company": "15586",
"Presidential Life Insurance Company": "68039",
"Primerica Life Insurance Company": "65919",
"Principal Life Insurance Company": "61271",
"Principal National Life Insurance Company": "71161",
"Proassurance Indemnity Company, Inc.": "33391",
"Procentury Insurance Company": "21903",
"Producers Agriculture Insurance Company": "34312",
"Professional Insurance Company": "68047",
"Professional Liability Insurance Company": "33359",
"Professional Liability Insurance Company Of America": "12513",
"Professional Solutions Insurance Company": "11127",
"Professional Underwriters Liability Insurance Company": "34487",
"Professionals Advocate Insurance Company": "29017",
"Professionals Direct Insurance Company": "25585",
"Progressive Advanced Insurance Company": "11851",
"Progressive Choice Insurance Company": "44288",
"Progressive Direct Insurance Company": "16322",
"Progressive Express Insurance Company": "10193",
"Progressive Northwestern Insurance Company": "42919",
"Progressive Specialty Insurance Company": "32786",
"Progressive West Insurance Company": "27804",
"Property and Casualty Insurance Company Of Hartford": "34690",
"Protective Insurance Company": "12416",
"Protective Life and Annuity Insurance Company": "88536",
"Protective Life Insurance Company": "68136",
"Providence Washington Insurance Company": "24295",
"Provident American Life & Health Insurance Company": "67903",
"Provident Life and Accident Insurance Company": "68195",
"Pruco Life Insurance Company": "79227",
"Prudential Annuities Life Assurance Corporation": "86630",
"Prudential Insurance Company Of America (The)": "68241",
"Prudential Retirement Insurance and Annuity Company": "93629",
"Public Service Mutual Insurance Company": "15059",
"Putnam Reinsurance Company": "35157",
"Pxre Reinsurance Company": "29807",
"Pyramid Life Insurance Company (The)": "68284",
"Qbe Insurance Corporation": "39217",
"Qbe Reinsurance Corporation": "10219",
"Quanta Indemnity Company": "23752",
"R&Q Reinsurance Company": "22705",
"R.V.I. America Insurance Company": "10344",
"R.V.I. National Insurance Company": "23132",
"Radian Asset Assurance Inc.": "36250",
"Radian Guaranty Inc.": "33790",
"Rampart Insurance Company": "38512",
"Reassure America Life Insurance Company": "70211",
"Red Shield Insurance Company": "41580",
"Redland Insurance Company": "37303",
"Redwood Fire and Casualty Insurance Company": "11673",
"Regent Insurance Company": "24449",
"Reinsurance Company Of America, Inc.": "26549",
"Reliable Life Insurance Company (The)": "68357",
"Reliance Life Insurance Company": "72613",
"Reliance Standard Life Insurance Company": "68381",
"Reliastar Life Insurance Company": "67105",
"Reliastar Life Insurance Company Of New York": "61360",
"Renaissance Life & Health Insurance Company Of America": "61700",
"Republic Indemnity Company Of America": "22179",
"Republic Indemnity Company Of California": "43753",
"Republic Mortgage Insurance Company": "28452",
"Republic Mortgage Insurance Company Of Florida": "32174",
"Republic Mortgage Insurance Company Of North Carolina": "31275",
"Republic Underwriters Insurance Company": "24538",
"Republic Western Insurance Company": "31089",
"Residence Mutual Insurance Company": "15776",
"Resource Life Insurance Company": "61506",
"Response Indemnity Company Of California": "10970",
"Response Insurance Company": "43044",
"Response Worldwide Insurance Company": "26050",
"Rga Reinsurance Company": "93572",
"Riverport Insurance Company": "36684",
"Riversource Life Insurance Company": "65005",
"Rli Indemnity Company": "28860",
"Rli Insurance Company": "13056",
"Rochdale Insurance Company": "12491",
"Rocky Mountain Fire & Casualty Company": "22128",
"Royal Neighbors Of America": "57657",
"Rsui Indemnity Company": "22314",
"Rural Community Insurance Company": "39039",
"S.Usa Life Insurance Company, Inc.": "60183",
"Safehealth Life Insurance Company": "79014",
"Safety First Insurance Company": "11123",
"Safety National Casualty Corporation": "15105",
"Safeway Direct Insurance Company": "10939",
"Safeway Insurance Company": "12521",
"Safeway Insurance Company Of Georgia": "25640",
"Sagamore Insurance Company": "40460",
"Sagicor Life Insurance Company": "60445",
"Samsung Fire & Marine Insurance Co., Ltd. (United States Branch)": "38300",
"San Diego Insurance Company": "10837",
"San Francisco Reinsurance Company": "21911",
"Savings Bank Life Insurance Company Of Massachusetts (The)": "70435",
"Scor Global Life Re Insurance Company Of Texas": "87017",
"Scor Life U.S. Re Insurance Company": "64688",
"Scor Reinsurance Company": "30058",
"Scottish Re (U.S.), Inc.": "87572",
"Scottish Re Life Corporation": "90670",
"Scottsdale Indemnity Company": "15580",
"Scpie Indemnity Company": "10352",
"Seabright Insurance Company": "15563",
"Sears Life Insurance Company": "69914",
"Seaton Insurance Company": "25763",
"Seaworthy Insurance Company": "37923",
"Securian Casualty Company": "10054",
"Securian Life Insurance Company": "93742",
"Security Benefit Life Insurance Company": "68675",
"Security Life Insurance Company Of America": "68721",
"Security Life Of Denver Insurance Company": "68713",
"Security Mutual Life Insurance Company Of New York": "68772",
"Security National Insurance Company": "19879",
"Security National Life Insurance Company": "69485",
"Security Union Title Insurance Company": "50857",
"Select Insurance Company": "22233",
"Selective Insurance Company Of America": "12572",
"Seneca Insurance Company, Inc.": "10936",
"Senior Health Insurance Company Of Pennsylvania": "76325",
"Sentinel Security Life Insurance Company": "68802",
"Sentry Casualty Company": "28460",
"Sentry Insurance A Mutual Company": "24988",
"Sentry Life Insurance Company": "68810",
"Sentry Select Insurance Company": "21180",
"Sequoia Insurance Company": "22985",
"Service Insurance Company": "36560",
"Settlers Life Insurance Company": "97241",
"Sierra Health and Life Insurance Company, Inc.": "71420",
"Slovene National Benefit Society": "57673",
"Sompo Japan Fire & Marine Insurance Company Of America": "38997",
"Sompo Japan Insurance Company Of America": "11126",
"Sons Of Norway": "57142",
"Southern Insurance Company": "19216",
"Sparta Insurance Company": "20613",
"Springfield Insurance Company": "36790",
"St. Paul Fire and Marine Insurance Company": "24767",
"St. Paul Guardian Insurance Company": "24775",
"St. Paul Medical Liability Insurance Company": "41750",
"St. Paul Mercury Insurance Company": "24791",
"St. Paul Protective Insurance Company": "19224",
"Standard Guaranty Insurance Company": "42986",
"Standard Insurance Company": "69019",
"Standard Life and Accident Insurance Company": "86355",
"Standard Life Insurance Company Of Indiana": "69051",
"Standard Security Life Insurance Company Of New York": "69078",
"Star Insurance Company": "18023",
"Starmount Life Insurance Company": "68985",
"Starnet Insurance Company": "40045",
"Starr Indemnity & Liability Company": "38318",
"State Compensation Insurance Fund": "35076",
"State Farm Annuity and Life Insurance Company": "94498",
"State Farm Life Insurance Company": "69108",
"State Life Insurance Company (The)": "69116",
"State National Insurance Company, Inc.": "12831",
"Sterling Casualty Insurance Company": "12878",
"Sterling Investors Life Insurance Company": "89184",
"Sterling Life Insurance Company": "77399",
"Stewart Title Guaranty Company": "50121",
"Stewart Title Insurance Company": "51420",
"Stonebridge Casualty Insurance Company": "10952",
"Stonebridge Life Insurance Company": "65021",
"Stonewall Insurance Company": "22276",
"Stonington Insurance Company": "10340",
"Stratford Insurance Company": "40436",
"Sua Insurance Company": "40134",
"Suecia Insurance Company": "39187",
"Sun Life and Health Insurance Company (U.S.)": "80926",
"Sun Life Assurance Company Of Canada": "80802",
"Sun Life Assurance Company Of Canada (U.S.)": "79065",
"Sun Surety Insurance Company": "10909",
"Sunamerica Annuity and Life Assurance Company": "60941",
"Sunamerica Life Insurance Company": "69256",
"Sunset Life Insurance Company Of America": "69272",
"Superior Insurance Company": "12220",
"Supreme Council Of The Royal Arcanum": "58181",
"Suretec Insurance Company": "10916",
"Surety Bonding Company Of America": "24047",
"Surety Life Insurance Company": "69310",
"Sutter Insurance Company": "32107",
"Swiss Re Life & Health America Inc.": "82627",
"Swiss Reinsurance America Corporation": "25364",
"Symetra Life Insurance Company": "68608",
"Symetra National Life Insurance Company": "90581",
"Syncora Guarantee Inc.": "20311",
"Teachers Insurance and Annuity Association Of America": "69345",
"Texas General Indemnity Company": "19526",
"Texas Life Insurance Company": "69396",
"Thrivent Financial For Lutherans": "56014",
"Thrivent Life Insurance Company": "97721",
"Tiaa-Cref Life Insurance Company": "60142",
"Ticor Title Insurance Company": "50067",
"Ticor Title Insurance Company Of Florida": "51535",
"Tig Indemnity Company": "25496",
"Tig Insurance Company": "25534",
"Time Insurance Company": "69477",
"Titan Indemnity Company": "13242",
"Tnus Insurance Company": "32301",
"Toa Reinsurance Company Of America (The)": "42439",
"Tokio Marine & Nichido Fire Insurance Co., Ltd.": "12904",
"Topa Insurance Company": "18031",
"Tower Insurance Company Of New York": "44300",
"Toyota Motor Insurance Company": "37621",
"Trans Pacific Insurance Company": "41238",
"Trans World Assurance Company": "69566",
"Transamerica Financial Life Insurance Company": "70688",
"Transamerica Life Insurance Company": "86231",
"Transatlantic Reinsurance Company": "19453",
"Transguard Insurance Company Of America, Inc": "28886",
"Transport Insurance Company": "33014",
"Transportation Insurance Company": "20494",
"Transunion Title Insurance Company": "50849",
"Travelers Casualty Company Of Connecticut": "36170",
"Travelers Commercial Insurance Company": "36137",
"Travelers Indemnity Company Of Connecticut (The)": "25682",
"Travelers Property Casualty Company Of America": "25674",
"Travelers Protective Association Of America (The)": "56006",
"Trenwick America Reinsurance Corporation": "34894",
"Triad Guaranty Insurance Corporation": "24350",
"Trinity Universal Insurance Company": "19887",
"Triton Insurance Company": "41211",
"Triumphe Casualty Company": "41106",
"Trumbull Insurance Company": "27120",
"Trustmark Insurance Company": "61425",
"Trustmark Life Insurance Company": "62863",
"Twin City Fire Insurance Company": "29459",
"U.S. Financial Life Insurance Company": "84530",
"U.S. Specialty Insurance Company": "29599",
"Ubs Life Insurance Company Usa": "67423",
"Ullico Casualty Company": "37893",
"Ullico Life Insurance Company": "86371",
"Underwriter For The Professions Insurance Company": "41050",
"Unicare Life & Health Insurance Company": "80314",
"Unified Life Insurance Company": "11121",
"Unigard Insurance Company": "25747",
"Unimerica Insurance Company": "91529",
"Union Bankers Insurance Company": "69701",
"Union Central Life Insurance Company (The)": "80837",
"Union Fidelity Life Insurance Company": "62596",
"Union Labor Life Insurance Company (The)": "69744",
"Union Security Insurance Company": "70408",
"United American Insurance Company": "92916",
"United Benefit Life Insurance Company": "65269",
"United Capital Title Insurance Company": "50041",
"United Casualty Insurance Company Of America": "11142",
"United Concordia Insurance Company": "85766",
"United Farm Family Life Insurance Company": "69892",
"United Fidelity Life Insurance Company": "87645",
"United Financial Casualty Company": "11770",
"United Fire & Casualty Company": "13021",
"United General Title Insurance Company": "51624",
"United Guaranty Commercial Insurance Company Of North Carolina": "16659",
"United Guaranty Credit Insurance Company": "40525",
"United Guaranty Mortgage Indemnity Company": "26999",
"United Guaranty Residential Insurance Company": "15873",
"United Healthcare Insurance Company": "79413",
"United Heritage Life Insurance Company": "63983",
"United Home Life Insurance Company": "69922",
"United Insurance Company Of America": "69930",
"United Investors Life Insurance Company": "94099",
"United National Casualty Insurance Company": "11445",
"United National Specialty Insurance Company": "41335",
"United Of Omaha Life Insurance Company": "69868",
"United Security Assurance Company Of Pennsylvania": "42129",
"United States Fidelity and Guaranty Company": "25887",
"United States Fire Insurance Company": "21113",
"United States Letter Carriers' Mutual Benefit Association Of and For The National Association Of Letter Carriers": "56456",
"United States Life Insurance Company In The City Of New York (The)": "70106",
"United Teacher Associates Insurance Company": "63479",
"United Transportation Union Insurance Association": "56413",
"United Wisconsin Insurance Company": "29157",
"United World Life Insurance Company": "72850",
"Unitrin Auto and Home Insurance Company": "16063",
"Unitrin Direct Insurance Company": "10226",
"Unitrin Direct Property & Casualty Company": "10915",
"Unity Financial Life Insurance Company": "63819",
"Unity Mutual Life Insurance Company": "70114",
"Universal Casualty Company": "42862",
"Universal Life Insurance Company": "70157",
"Universal North America Insurance Company": "10759",
"Universal Surety Of America": "13200",
"Universal Underwriters Insurance Company": "41181",
"Universal Underwriters Life Insurance Company": "70173",
"Unum Life Insurance Company Of America": "62235",
"Upper Hudson National Insurance Company": "29998",
"Usa Life One Insurance Company Of Indiana": "70955",
"USAA General Indemnity Company": "18600",
"Usaa Life Insurance Company": "69663",
"Usable Life": "94358",
"Usplate Glass Insurance Company": "28497",
"Utica Mutual Insurance Company": "25976",
"Valiant Insurance Company": "26611",
"Valley Forge Insurance Company": "20508",
"Valley Insurance Company": "14133",
"Vanliner Insurance Company": "21172",
"Vantislife Insurance Company": "68632",
"Variable Annuity Life Insurance Company (The)": "70238",
"Verlan Fire Insurance Company": "10815",
"Veterinary Pet Insurance Company": "42285",
"Victoria Fire & Casualty Company": "42889",
"Vigilant Insurance Company": "20397",
"Viking Insurance Company Of Wisconsin": "13137",
"Vintage Insurance Company": "10079",
"Virginia Surety Company, Inc.": "40827",
"Vista Life Insurance Company": "84549",
"Washington International Insurance Company": "32778",
"Washington National Insurance Company": "70319",
"Wausau Business Insurance Company": "26069",
"Wausau Underwriters Insurance Company": "26042",
"Wawanesa General Insurance Company": "10683",
"Wawanesa Mutual Insurance Company (The)": "31526",
"Wellcare Health Insurance Of Illinois, Inc.": "64467",
"Wellington Life Insurance Company": "85537",
"Wesco Insurance Company": "25011",
"West Coast Life Insurance Company": "70335",
"Westchester Fire Insurance Company": "21121",
"Westcor Land Title Insurance Company": "50050",
"Western and Southern Life Insurance Company (The)": "70483",
"Western Fraternal Life Association": "58017",
"Western General Insurance Company": "27502",
"Western Home Insurance Company": "26395",
"Western Insurance Company": "10008",
"Western National Life Insurance Company": "70432",
"Western Reserve Life Assurance Co Of Ohio": "91413",
"Western Select Insurance Company": "10997",
"Western Surety Company": "13188",
"Western Underwriters Insurance Company": "10935",
"Western United Insurance Company": "37770",
"Western-Southern Life Assurance Company": "92622",
"Westfield National Insurance Company": "24120",
"Westport Insurance Corporation": "39845",
"Westward Insurance Company": "24635",
"Westward Life Insurance Company": "78301",
"White Mountains Reinsurance Company Of America": "38776",
"William Penn Association": "57010",
"Williamsburg National Insurance Company": "25780",
"Wilshire Insurance Company": "13234",
"Wilton Reassurance Company": "66133",
"Wilton Reassurance Life Company Of New York": "60704",
"Woman'S Life Insurance Society": "56170",
"Woodmen Of The World": "56499",
"Work First Casualty Company": "31232",
"Workmen'S Auto Insurance Company": "13250",
"Workmen'S Benefit Fund Of The United States Of America": "57290",
"Workmen'S Life Insurance Company": "78409",
"World Insurance Company": "70629",
"Xl Insurance America, Inc.": "24554",
"Xl Insurance Company Of New York, Inc.": "40193",
"Xl Life Insurance and Annuity Company": "88080",
"Xl Re Life America Inc.": "80586",
"Xl Reinsurance America Inc.": "20583",
"Xl Specialty Insurance Company": "37885",
"York Insurance Company": "24325",
"Yosemite Insurance Company": "26220",
"Zale Indemnity Company": "30325",
"Zale Life Insurance Company": "71323",
"Zenith Insurance Company": "13269",
"Znat Insurance Company": "30120",
"Zurich American Insurance Company": "16535",
"Zurich American Insurance Company Of Illinois": "27855"
  };

  
  const rows = Array.from({length: 1307}, (_, i) => i + 1);

  rows.forEach(i => {
    const insurerSelect = document.getElementById(`insurer${i}`);
    const websiteInput = document.getElementById(`website${i}`);
    const naicInput = document.getElementById(`naic${i}`);

    if (insurerSelect && websiteInput && naicInput) {
      insurerSelect.addEventListener("change", function () {
        const selected = this.value;
        websiteInput.value = insurerWebsites[selected] || "";
        naicInput.value = insurerNaic[selected] || "";
      });
    }
  });
});


// Save button functionality
const saveButton = document.getElementById('saveButton');

saveButton.addEventListener('click', async (e) => {
  e.preventDefault();

  const agentName = document.getElementById('agentName').value;
  const individualCaLicense = document.getElementById('individualCaLicense').value;
  const agencyName = document.getElementById('agencyName').value;
  const agencyCaLicense = document.getElementById('agencyCaLicense').value;
  const nameOfInsured = document.getElementById('nameOfInsured').value;
  const descriptionRisk = document.getElementById('descriptionRisk').value;
  const coverageCode = document.getElementById('coverageCode').value;

  //Validation checks
  if (!agentName) {
    alert("Please fill Agent Name. Required field.");
    return;
  }

  if (!agencyName && agencyCaLicense && !individualCaLicense) {
    alert("Please fill Agency Name or provide the Individual CA License Number. Required field.");
    return;
  }

   if (!agencyName && agencyCaLicense ) {
    alert("Please fill Agency Name. Required field.");
    return;
  }

  if (agencyName && !agencyCaLicense) {
    alert("Please fill Agency Code. Required field.");
    return;
  }

  if (!agencyName && !agencyCaLicense && !individualCaLicense) {
    alert("Please fill Agent CA License Number, or fill the Agency Name and Agency CA License Number fields. Required field.");
    return;
  }

  if (!nameOfInsured) {
    alert("Please fill Name of Insured. Required field.");
    return;
  }

  if (!descriptionRisk) {
    alert("Please fill Descriptions Risk. Required field.");
    return;
  }

  if (!coverageCode) {
    alert("Please Select Coverage Code. Required field.");
    return;
  }

  const insurer1 = document.getElementById('insurer1').value;
  const contactedThrough1 = document.getElementById('contactedThrough1').value;
  const fullContactName1 = document.getElementById('fullContactName1').value;
  const emailPhone1 = document.getElementById('email-phone1').value;
  const naic1 = document.getElementById('naic1').value;
  const date1 = document.getElementById('date1').value;
  const website1 = document.getElementById('website1').value;

  // Validation checks insurer1
  if (agentName.trim().toLowerCase().replace(/\s+/g, " ") === fullContactName1.trim().toLowerCase().replace(/\s+/g, " ") ) {
    alert("The insurer and contacted  fields cannot be the same.");
    return;
  }

  if (!contactedThrough1){
    alert("Please fill in the contacted through field at Insurer 1.");
    return;
  }

  if (contactedThrough1.trim().toLowerCase() === "online" && !document.getElementById('website1').value){
    alert("Please fill in the website field.");
    return;
  }

  if (contactedThrough1.trim().toLowerCase() !== "online" && !document.getElementById('email-phone1').value){
    alert("Please fill in the email/phone insurer of insurer 1 field.");
    return;
  }

  if (contactedThrough1.trim().toLowerCase() !== "online" && !fullContactName1){
    alert("Please fill in the Full Contact Name of the Insurer 1 field.");
    return;
    }

  if (!date1){
    alert("Please fill in the date field at Insurer 1.");
    return;
  }

  const insurer2 = document.getElementById('insurer2').value;
  const contactedThrough2 = document.getElementById('contactedThrough2').value;
  const fullContactName2 = document.getElementById('fullContactName2').value;
  const emailPhone2 = document.getElementById('email-phone2').value;
  const naic2 = document.getElementById('naic2').value;
  const date2 = document.getElementById('date2').value;
  const website2 = document.getElementById('website2').value;


  // Validation checks insurer2

  if (agentName.trim().toLowerCase().replace(/\s+/g," ") === fullContactName2.trim().toLowerCase().replace(/\s+/g, " ") ) {
    alert("The insurer and contacted  fields cannot be the same.");
    return;
  }

   if (!contactedThrough2){
    alert("Please fill in the contacted through field at Insurer 2.");
    return;
  }
  


  if (contactedThrough2.trim().toLowerCase() === "online" && !document.getElementById('website2').value){
    alert("Please fill in the website field.");
    return;
  }

  if (contactedThrough2.trim().toLowerCase() !== "online" && !document.getElementById('email-phone2').value){
    alert("Please fill in the email/phone field of the Insurer 2 .");
    return;
  }

  if (contactedThrough2.trim().toLowerCase() !== "online" && !fullContactName2){
    alert("Please fill in the Full Contact Name of the Insurer 2 field.");
    return;
    }


  if (!date2){
    alert("Please fill in the date field at Insurer 2.");
    return;
  }

  const insurer3 = document.getElementById('insurer3').value;
  const contactedThrough3 = document.getElementById('contactedThrough3').value;
  const fullContactName3 = document.getElementById('fullContactName3').value;
  const emailPhone3 = document.getElementById('email-phone3').value;
  const naic3 = document.getElementById('naic3').value;
  const date3 = document.getElementById('date3').value;
  const website3 = document.getElementById('website3').value;


  // Validation checks insurer3
 if (agentName.trim().toLowerCase().replace(/\s+/g, " ") === fullContactName3.trim().toLowerCase().replace(/\s+/g, " ") ) {
    alert("The insurer and contacted  fields cannot be the same.");
    return;
  }
  if (!contactedThrough3){
    alert("Please fill in the contacted through field at Insurer 3.");
    return;
  }
 if (contactedThrough3.trim().toLowerCase() === "online" && !document.getElementById('website3').value){
    alert("Please fill in the website field.");
    return;
  }

  if (contactedThrough3.trim().toLowerCase() !== "online" && !document.getElementById('email-phone3').value){
    alert("Please fill in the email/phone of the Insurer 3 field.");
    return;
  }

  if (contactedThrough3.trim().toLowerCase() !== "online" && !fullContactName3){
    alert("Please fill in the Full Contact Name of the Insurer 3 field.");
    return;
    }
   if (!date3){
    alert("Please fill in the date field at Insurer 3.");
    return;
  }
  

  const signatureDate = document.getElementById('signatureDate').value;

  if (!signatureDate){
    alert("Please fill in the Signature date field at Insurer 3.");
    return;
  }

  // Log all data
  console.log(agentName, individualCaLicense, agencyName, agencyCaLicense, nameOfInsured, descriptionRisk, coverageCode);
  console.log(insurer1, contactedThrough1, fullContactName1, emailPhone1, naic1, date1);
  console.log(insurer2, contactedThrough2, fullContactName2, emailPhone2, naic2, date2);
  console.log(insurer3, contactedThrough3, fullContactName3, emailPhone3, naic3, date3);
  console.log(signatureDate);

// PDF Generation with pdf-lib
  const { PDFDocument , StandardFonts} = window.PDFLib;

 const pdfLoaded = await fetch('sl2form.pdf').then(res => res.arrayBuffer());
 const pdfDoc = await PDFDocument.load(pdfLoaded);

  const pages = pdfDoc.getPages();
  const page = pages[0];

  const font = await pdfDoc.embedFont(StandardFonts.TimesRoman);

  page.drawText(agentName, { x: 65, y: 720, size: 12, font: font });
  page.drawText(individualCaLicense, { x: 210, y: 677, size: 12, font: font });
  page.drawText(agencyName, { x: 270, y: 666, size: 12, font: font });
  page.drawText(agencyCaLicense,{ x: 320, y: 653, size: 12, font: font });
  page.drawText(nameOfInsured, { x: 148, y: 625, size: 12, font: font });
  page.drawText(descriptionRisk, { x: 152, y: 610, size: 12, font: font });
  page.drawText(coverageCode, { x: 230, y: 580, size: 12, font: font });

  // Draw details for insurer 1
  page.drawText(naic1, { x: 29, y: 448, size: 12, font: font });
  page.drawText(date1, { x: 118, y: 448, size: 12, font: font });
  page.drawText(insurer1, { x: 29, y: 415, size: 7, font: font });

    if (contactedThrough1.trim().toLowerCase() === "online") {
     page.drawText("Online", { x: 29, y: 372, size: 12, font: font });
     page.drawText(website1, { x: 29, y: 307,size: 8, font: font });

    } else {
    page.drawText(fullContactName1, {x: 29, y: 372, size: 12, font: font });
    page.drawText(emailPhone1, { x: 29, y: 338, size: 12, font: font });
    }

  // Draw details for insurer 2
  page.drawText(naic2, { x: 212, y: 448, size: 12, font: font });
  page.drawText(date2, { x: 300, y: 448, size: 12, font: font });
  page.drawText(insurer2, { x: 212, y: 415, size: 7, font: font });
  
  if (contactedThrough2.trim().toLowerCase() === "online") {
     page.drawText("Online", { x: 212, y: 372, size: 12, font: font });
     page.drawText(website2, { x: 212, y: 307,size: 8, font: font });
    } else {
  page.drawText(fullContactName2, {x: 212, y: 372, size: 12, font: font });
  page.drawText(emailPhone2, { x: 212, y: 338, size: 12, font: font });
  
  }

  // Draw details for insurer 3
  page.drawText(naic3, { x: 395, y: 448, size: 12, font: font });
  page.drawText(date3, { x: 482, y: 448, size: 12, font: font });
  page.drawText(insurer3, { x: 395, y: 415, size: 7, font: font });
  
  if (contactedThrough3.trim().toLowerCase() === "online") {
     page.drawText("Online", { x: 395, y: 372, size: 12, font: font });
     page.drawText(website3, { x: 395, y: 307,size: 8, font: font });
    } else {
  page.drawText(fullContactName3, {x: 395, y: 372, size: 12, font: font });
  page.drawText(emailPhone3, { x: 395, y: 338, size: 12, font: font });
 } 
 
page.drawText("x", { x: 140, y: 202, size: 12, font: font }); 
 page.drawText(signatureDate, { x: 420, y: 92, size: 12, font: font });

  // Save the PDF and prompt download
  const pdfBytes = await pdfDoc.save();

  // Create a Blob for downloading
  const pdfBlob = new Blob([pdfBytes], { type: 'application/pdf' });
  const pdfUrl = URL.createObjectURL(pdfBlob);

  // Trigger file download
  const link = document.createElement('a');
  link.href = pdfUrl;
  link.download = 'insurance_form_details.pdf';
  link.click();


});

